"""Checklist 4.4 verification — unit-level (no Streamlit).

Covers: sheet-name sanitization (invalid chars, >31 char truncation,
blank fallback, case-insensitive de-duplication that still respects the
31-char limit with a suffix appended); filename sanitization (normal,
blank, special characters, Windows trailing dot/space rule,
fully-invalid names); a real workbook built against the actual seeded
schema producing exactly 2 sheets matching the 10-item and 13-item
tables, with correct headers/formatting/verbatim requirement text;
manual edits (a hand-built results_store) appearing exactly in the
generated bytes; a reconfigured schema with different table counts,
custom names, special characters, and a genuine sheet-name collision
producing valid, openable files; and the empty/zero-table/zero-column
edge cases.

Every workbook built in this suite is round-tripped through
openpyxl.load_workbook() on its exported bytes - the most direct proof
of "produces valid, openable Excel files."

Run: python tests/verify_excel_export_unit.py
"""
from __future__ import annotations

import io
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from openpyxl import load_workbook  # noqa: E402

from db import crud  # noqa: E402
from db.connection import get_connection  # noqa: E402
from db.schema import init_db  # noqa: E402
from export.excel_export import (  # noqa: E402
    DEFAULT_FILENAME,
    EXPORT_HEADERS,
    MAX_SHEET_NAME_LENGTH,
    build_workbook,
    sanitize_filename,
    sanitize_sheet_name,
    workbook_to_bytes,
)
from seed.seed_data import TABLE_1_ITEMS, TABLE_2_ITEMS  # noqa: E402
from seed.seeder import seed_if_empty  # noqa: E402
from verify.groq_verifier import VerificationResult  # noqa: E402

checks: list[tuple[str, bool]] = []


def check(label: str, condition: bool) -> None:
    checks.append((label, bool(condition)))
    print(f"{'OK  ' if condition else 'FAIL'} {label}")


def assert_openable(data: bytes, label: str) -> None:
    try:
        load_workbook(io.BytesIO(data))
        check(f"{label} -> produces a valid, openable Excel file", True)
    except Exception as exc:  # noqa: BLE001
        check(f"{label} -> produces a valid, openable Excel file ({exc})", False)


def make_db(tmp_dir: str, name: str):
    db_path = str(Path(tmp_dir) / name)
    conn = get_connection(db_path)
    init_db(conn)
    return conn


def result(pdf="a.pdf", page="1", confidence=0.9, snippet="snip", success=True) -> VerificationResult:
    return VerificationResult(
        pdf_name=pdf, page_number_or_range=page, confidence=confidence,
        match_snippet=snippet, reasoning="r", success=success,
    )


# --------------------------------------------------------- sheet names --


def test_sanitize_sheet_name() -> None:
    existing: set[str] = set()
    check("normal name unchanged", sanitize_sheet_name("Table 1", existing) == "Table 1")

    existing2: set[str] = set()
    dirty = "Table/A:B*C[D]E?F\\G"
    cleaned = sanitize_sheet_name(dirty, existing2)
    check("invalid Excel chars (\\/?*[]:) all replaced", not any(ch in cleaned for ch in "\\/?*[]:"))

    existing3: set[str] = set()
    long_name = "A" * 50
    truncated = sanitize_sheet_name(long_name, existing3)
    check(f"names > {MAX_SHEET_NAME_LENGTH} chars are truncated", len(truncated) == MAX_SHEET_NAME_LENGTH)

    existing4: set[str] = set()
    check("blank name falls back to a non-empty default", sanitize_sheet_name("   ", existing4) != "")
    check("all-invalid-character name falls back to a non-empty default", sanitize_sheet_name("///:::", set()) != "")

    existing5: set[str] = set()
    first = sanitize_sheet_name("Duplicate", existing5)
    second = sanitize_sheet_name("Duplicate", existing5)
    third = sanitize_sheet_name("DUPLICATE", existing5)  # case-insensitive collision with the first two
    check("exact duplicate names are disambiguated", first != second)
    check("case-insensitive duplicate ('DUPLICATE' vs 'Duplicate') is also disambiguated", third not in (first, second))
    check("all three disambiguated names are still <= max length", all(len(n) <= MAX_SHEET_NAME_LENGTH for n in (first, second, third)))

    existing6: set[str] = set()
    long_dup_1 = sanitize_sheet_name("B" * 40, existing6)
    long_dup_2 = sanitize_sheet_name("B" * 40, existing6)
    check("a long name colliding with itself still disambiguates within the 31-char limit", long_dup_1 != long_dup_2 and len(long_dup_2) <= MAX_SHEET_NAME_LENGTH)


# ------------------------------------------------------------ filenames --


def test_sanitize_filename() -> None:
    check("normal company name -> '<name>.xlsx'", sanitize_filename("ABC Pharma Pvt Ltd") == "ABC Pharma Pvt Ltd.xlsx")
    check("blank name -> DEFAULT_FILENAME", sanitize_filename("") == DEFAULT_FILENAME)
    check("whitespace-only name -> DEFAULT_FILENAME", sanitize_filename("   ") == DEFAULT_FILENAME)
    check("None-like/falsy input handled without raising", sanitize_filename(None) == DEFAULT_FILENAME)

    special = sanitize_filename('A/B:C*D?E"F<G>H|I')
    check("filesystem-invalid characters are replaced, not left in the filename", not any(ch in special for ch in '/:*?"<>|'))
    check("sanitized filename still ends in .xlsx", special.endswith(".xlsx"))

    check("trailing dot/space (Windows-invalid) is stripped before appending .xlsx", sanitize_filename("Company Name.  ") == "Company Name.xlsx")
    dirty_input = "////:::???"
    check(
        "invalid filesystem characters are replaced with underscores, not emptied out",
        sanitize_filename(dirty_input) == ("_" * len(dirty_input)) + ".xlsx",
    )
    check(
        "a name that's ONLY dots/spaces (all stripped away, nothing left) falls back to DEFAULT_FILENAME",
        sanitize_filename("...   ...") == DEFAULT_FILENAME,
    )


# --------------------------------------------------------- seeded schema --


def test_seeded_schema_produces_two_matching_sheets() -> None:
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as tmp:
        conn = make_db(tmp, "seeded.db")
        seed_if_empty(conn)

        wb = build_workbook(conn, {})
        check("seeded schema -> exactly 2 sheets", len(wb.sheetnames) == 2)
        check("sheet names are 'Table 1' and 'Table 2'", set(wb.sheetnames) == {"Table 1", "Table 2"})

        ws1 = wb["Table 1"]
        ws2 = wb["Table 2"]
        check("'Table 1' sheet has 10 data rows (+ 1 header = 11)", ws1.max_row == 11)
        check("'Table 2' sheet has 13 data rows (+ 1 header = 14)", ws2.max_row == 14)

        check("header row matches EXPORT_HEADERS exactly", [c.value for c in ws1[1]] == EXPORT_HEADERS)
        check("header cells are bold", all(c.font.bold for c in ws1[1]))
        check("header row is frozen (freeze_panes == 'A2')", ws1.freeze_panes == "A2")

        requirement_col = EXPORT_HEADERS.index("Requirement") + 1
        actual_reqs = [ws1.cell(row=r, column=requirement_col).value for r in range(2, 12)]
        expected_reqs = [text for _name, text in TABLE_1_ITEMS]
        check("Table 1's Requirement column matches the real seed text VERBATIM, in order", actual_reqs == expected_reqs)

        actual_reqs2 = [ws2.cell(row=r, column=requirement_col).value for r in range(2, 15)]
        expected_reqs2 = [text for _name, text in TABLE_2_ITEMS]
        check("Table 2's Requirement column matches the real seed text VERBATIM, in order", actual_reqs2 == expected_reqs2)

        status_col = EXPORT_HEADERS.index("Status") + 1
        check("every row's Status is 'Flagged' when no results are supplied at all", all(ws1.cell(row=r, column=status_col).value == "Flagged" for r in range(2, 12)))

        req_cell = ws1.cell(row=2, column=requirement_col)
        snippet_cell = ws1.cell(row=2, column=EXPORT_HEADERS.index("Match Snippet") + 1)
        check("Requirement cells have wrap_text alignment", req_cell.alignment.wrap_text is True)
        check("Match Snippet cells have wrap_text alignment", snippet_cell.alignment.wrap_text is True)
        check("column widths are set for all 6 columns", all(ws1.column_dimensions[l].width for l in "ABCDEF"))

        assert_openable(workbook_to_bytes(wb), "seeded schema workbook")


def test_manual_edit_appears_exactly_in_export() -> None:
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as tmp:
        conn = make_db(tmp, "edit.db")
        seed_if_empty(conn)

        results_store = {
            4: result(pdf="CompanyA_certificate.pdf", page="5-6", confidence=0.93, snippet="WHO-GMP certificate, valid until 2028."),
        }
        wb = build_workbook(conn, results_store)
        ws1 = wb["Table 1"]
        headers_idx = {h: i + 1 for i, h in enumerate(EXPORT_HEADERS)}
        row4 = 5  # column id 4 = Item 4 = data row index 4 -> spreadsheet row 2+3=5

        check("edited PDF Name appears exactly", ws1.cell(row=row4, column=headers_idx["PDF Name"]).value == "CompanyA_certificate.pdf")
        check("edited Page Number / Range appears exactly", ws1.cell(row=row4, column=headers_idx["Page Number / Range"]).value == "5-6")
        check("edited Confidence appears exactly (0.93)", ws1.cell(row=row4, column=headers_idx["Confidence"]).value == 0.93)
        check("Confidence cell number_format is '0.00'", ws1.cell(row=row4, column=headers_idx["Confidence"]).number_format == "0.00")
        check("edited Match Snippet appears exactly", ws1.cell(row=row4, column=headers_idx["Match Snippet"]).value == "WHO-GMP certificate, valid until 2028.")
        check("edited row's Status is 'Resolved' (confidence 0.93 >= 0.70)", ws1.cell(row=row4, column=headers_idx["Status"]).value == "Resolved")

        check("an UN-edited row (e.g. row 2, Item 1) is still 'Flagged'", ws1.cell(row=2, column=headers_idx["Status"]).value == "Flagged")
        check("the un-edited row's PDF Name is blank, not contaminated by the edit", ws1.cell(row=2, column=headers_idx["PDF Name"]).value in (None, ""))


# ----------------------------------------------- reconfigured schema --


def test_reconfigured_schema_custom_names_and_collision() -> None:
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as tmp:
        conn = make_db(tmp, "reconfig.db")

        # 3 tables: one with special characters, two that will SANITIZE
        # to the same name (a genuine collision), plus varying column
        # counts, none matching the seeded 10/13 shape.
        t1 = crud.create_table(conn, "Compliance/Docs:2026*")
        crud.create_column(conn, t1, "Req A", "Requirement text A for the reconfigured schema test.")
        crud.create_column(conn, t1, "Req B", "Requirement text B for the reconfigured schema test.")

        t2 = crud.create_table(conn, "Annex:X")
        crud.create_column(conn, t2, "Req C", "Requirement text C.")

        t3 = crud.create_table(conn, "Annex*X")  # sanitizes to the SAME name as t2 ("Annex_X")
        crud.create_column(conn, t3, "Req D", "Requirement text D.")
        crud.create_column(conn, t3, "Req E", "Requirement text E.")
        crud.create_column(conn, t3, "Req F", "Requirement text F.")

        wb = build_workbook(conn, {})
        check("3 tables configured -> exactly 3 sheets", len(wb.sheetnames) == 3)
        check("no sheet name contains an Excel-invalid character", all(not any(ch in name for ch in "\\/?*[]:") for name in wb.sheetnames))
        check("the two colliding sanitized names ('Annex_X') were disambiguated into 2 distinct sheets", len(set(wb.sheetnames)) == 3)

        sheet_by_rowcount = {name: wb[name].max_row for name in wb.sheetnames}
        check("row counts match each table's actual column count (+1 header): 3, 2, 4", sorted(sheet_by_rowcount.values()) == [3, 2, 4] or sorted(sheet_by_rowcount.values()) == [2, 3, 4])

        assert_openable(workbook_to_bytes(wb), "reconfigured schema with special chars + name collision")


# ---------------------------------------------------------------- edges --


def test_empty_results_export_cleanly() -> None:
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as tmp:
        conn = make_db(tmp, "empty_results.db")
        seed_if_empty(conn)
        wb = build_workbook(conn, {})  # explicitly empty results_store
        check("empty results_store -> no crash, still 2 sheets", len(wb.sheetnames) == 2)
        assert_openable(workbook_to_bytes(wb), "empty results_store")

        wb_none = build_workbook(conn, None)  # the documented default
        check("results_store=None -> no crash, treated the same as {}", len(wb_none.sheetnames) == 2)


def test_zero_tables_export_cleanly() -> None:
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as tmp:
        conn = make_db(tmp, "zero_tables.db")
        # deliberately do NOT seed - zero tables configured
        wb = build_workbook(conn, {})
        check("zero tables -> workbook still has at least 1 sheet (Excel requires >= 1)", len(wb.sheetnames) >= 1)
        assert_openable(workbook_to_bytes(wb), "zero-table config")


def test_zero_column_table_exports_cleanly() -> None:
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as tmp:
        conn = make_db(tmp, "zero_cols.db")
        crud.create_table(conn, "Empty Table")  # a table with no columns at all
        wb = build_workbook(conn, {})
        ws = wb["Empty Table"]
        check("a zero-column table's sheet has only the header row", ws.max_row == 1)
        assert_openable(workbook_to_bytes(wb), "zero-column table")


def main() -> None:
    test_sanitize_sheet_name()
    test_sanitize_filename()
    test_seeded_schema_produces_two_matching_sheets()
    test_manual_edit_appears_exactly_in_export()
    test_reconfigured_schema_custom_names_and_collision()
    test_empty_results_export_cleanly()
    test_zero_tables_export_cleanly()
    test_zero_column_table_exports_cleanly()

    if all(ok for _, ok in checks):
        print(f"ALL CHECKS PASSED ({len(checks)}/{len(checks)})")
        sys.exit(0)
    else:
        failed = [label for label, ok in checks if not ok]
        print(f"FAILED {len(failed)}/{len(checks)}:")
        for label in failed:
            print(f"  - {label}")
        sys.exit(1)


if __name__ == "__main__":
    main()
